### ISSUE TITLE
Setting up a nav cube tutorial is broken

### ISSUE THREAD

**Issue by zhukoven** [ThatOpen/engine_docs#10]
Link to **Setting up a nav cube** tutorial (https://top-docs.vercel.app/docs/Tutorials/CubeMap.mdx) on page https://top-docs.vercel.app/docs/components/tutorial-paths results in error 404

> Documentation > Components > Tutorial paths >Making great 3D apps > Setting up a nav cube

**Comment by agviegas** [comment]
Hey! We've just made a huge update to the docs. Now the nav cube is called [view-cube](https://docs.thatopen.com/api/@thatopen/ui-obc/classes/ViewCube) is even easier to use, so no need to set it up - it comes as a premade web component. Let me know if you have any questions about it!
