### ISSUE TITLE
Update docs - highlighter.outlinesEnabled

### ISSUE THREAD

**Issue by daniel-augusto** [ThatOpen/engine_docs#12]
As registered in https://github.com/IFCjs/docs/issues/22, there is some documentation out of date.

This issue will update the references of ```highlighter.outlinesEnabled``` to ```highlighter.outlineEnabled``` as we can found in https://github.com/IFCjs/components/blob/main/src/fragments/FragmentHighlighter/index.ts#L85

**Comment by agviegas** [comment]
Docs updated!
