### ISSUE TITLE
PostproductionRenderer tutorial

### ISSUE THREAD

**Issue by sessionkiller** [ThatOpen/engine_docs#16]
Hi, in the tutorial for the [PostproductionRenderer](https://top-docs.vercel.app/docs/Tutorials/PostproductionRenderer) we should have the [absolute url](https://ifcjs.github.io/components/resources/small.frag) for the file instead for the relative one.

![image](https://github.com/IFCjs/docs/assets/13709104/454bf46e-bcff-42f8-875a-8e58b4be10b0)

Thanks.

**Comment by agviegas** [comment]
Fixed!
