### ISSUE TITLE
Documentation is already out of date

### ISSUE THREAD

**Issue by tristanradams** [ThatOpen/engine_docs#22]
### Describe the bug 📝

I am attempting to follow the documentation as closely as possible and there have been multiple instances where the documentation has been outright incorrect in regards to types and what is actually available.

Examples of instances of missing documented properties/methods:
- `components.scene.setup()`, where `setup()` does not exist
- `components.renderer.postproduction.customEffects.outlineEnabled = true`, where `postproduction` does not exist
- The docs say for the highlighter to use `highlighter.outlinesEnabled = true`, where the actual call is `highlighter.outlineEnabled = true`.

With running into just these few variances, there have to be multiple more. The variance between the documentation and the actual types can get frustrating and if types are included, they should accurately describe available functionality, methods, and properties.

### Steps to reproduce 🔢

1. Read the docs
2. Attempt to follow instructions exactly using a typescript project
3. Discover missing methods, properties.

### System Info 💻

```shell
Node, Vite, Typescript, MacOS
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://platform.thatopen.com/documentation).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a IFC.js components issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Documentation is now 100% up to date!
