### ISSUE TITLE
Update measurements example to delete unused CSS

### ISSUE THREAD

**Issue by HoyosJuan** [ThatOpen/engine_docs#23]
### Describe the bug 📝

Currently, the 3 dimensions examples are using CSS classes (.ifcjs-dimension-label, etc) that has no relevance as the applied styles in components are coming from Tailwind.

### System Info 💻

```shell
N/A
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://platform.thatopen.com/documentation).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/docs/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
This shouldn't apply anymore!
