### ISSUE TITLE
Clippin Planes Tutorial link redirects to wrong page

### ISSUE THREAD

**Issue by Rocha442** [ThatOpen/engine_docs#25]
### Describe the bug 📝

I was going through the Tutorial Path and realised the link embedeed in the "Create some clipping planes" redirects to the previous  SimpleRaycaster tutorial. I'm assuming this is a bug rather than the tutotial being outright unavailable :)

### Reproduction ▶️

https://docs.thatopen.com/components/tutorial-paths

### Steps to reproduce 🔢

1. Click on "Create some clipping planes" link in the Tutorial Path page (https://docs.thatopen.com/components/tutorial-paths)
2. Gets redirected to the wrong tutorial page (https://docs.thatopen.com/Tutorials/SimpleRaycaster)

![picture](https://github.com/IFCjs/docs/assets/152894583/e43574ac-af0b-4785-a7d6-c9cb2b1c4fe5)

### System Info 💻

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 5.98 GB / 15.89 GB
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.3636.0), Chromium (120.0.2210.61)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    openbim-components: ^1.2.0 => 1.2.0
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/docs/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Fixed! Let us know if there any more issues
