### ISSUE TITLE
Creating Components Tutorial, Retrieve Tools outdated.

### ISSUE THREAD

**Issue by ArturTecnet** [ThatOpen/engine_docs#26]
### Describe the bug 📝

In this [tutorial](https://docs.thatopen.com/components/creating-components) the retrieval of tools is explained like this:

const hwTool = await components.get(HelloWorldTool.uuid);

but it works with the tools attribute and without the uuid like this:

const hwTool = await components.tools.get(HelloWorldTool);

Also the tutorial should note, that the retrieval only works, if the components constructor doesn’t get other parameters than OBC.Components. If the class needs more to function, I would recommend to write a setup() Method that takes everything else.

### System Info 💻

```shell
Not needed since the error is in the content of the docs
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/docs/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Fixed!
