### ISSUE TITLE
Add indentations to code blocks for easy reading

### ISSUE THREAD

**Issue by HoyosJuan** [ThatOpen/engine_docs#32]
### Describe the bug 📝

Right now, code blocks in the documentation doesn't have indentations. Would be great to have them in order to better read the code.

### System Info 💻

```shell
N/A
```

### Used Package Manager 📦

yarn

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_docs/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Solved!
