### ISSUE TITLE
Missing documentation on how to locally develop

### ISSUE THREAD

**Issue by julillosamaral** [ThatOpen/engine_docs#8]
I notice it's not clear how to locally test the library.

I followed this: https://github.com/IFCjs/docs/blob/main/docs/components/contributing.md#start-coding

The issue with the three steps is that is not enough to test my changes locally. My case is that I'm using react to develop/test and not vanila js.

I saw on npm I can use `npm link` (https://docs.npmjs.com/cli/v10/commands/npm-link) to locally test the changes.

I did it and it works, the only problem is I had to follow the following process:
1. On components execute: `npm run build`
2. `cp package.json dist/`
3. `npm link`
4. Go to the project I'm using for development
5.  `npm link openbim-components`

Step 2 is the one I feel strange, maybe copying `package.json` inside the dist folder or have a command that does 1,2 and 3?

Besides that, I could work on the documentation to be more clear.

Thoughts?

**Comment by agviegas** [comment]
Hey, with the latest doc update, I added step-by-step instructions about how to develop locally! Let me know if you have any questions about them :)
